parameters:
#    hangman_api.example.class: Hangman\APIBundle\Example

services:
#    hangman_api.example:
#        class: %hangman_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
