parameters:
#    hangman_web.example.class: Hangman\WebBundle\Example

services:
#    hangman_web.example:
#        class: %hangman_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
